-------------------------------------------------------------------------
-- Creación de tablas para la BD del servicio de catering (Práctica 2) --
-------------------------------------------------------------------------

CREATE TABLE TIPO_PRODUCTO(
    ID INT AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BILINGUE(
    ID INT AUTO_INCREMENT NOT NULL,
    BILINGUE TINYINT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ROL_EMPLEADO(
    ID INT AUTO_INCREMENT NOT NULL,
    ROL VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ESTADO(
    ID INT AUTO_INCREMENT NOT NULL,
    ESTADO VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO(
  CODIGO VARCHAR(5) NOT NULL,
  NOMBRE VARCHAR(25) NOT NULL,
  DESCRIPCION VARCHAR(150),
  CADUCIDAD DATE NOT NULL,
  TIPO_PRODUCTO_ID INT NOT NULL,
  PRIMARY KEY (CODIGO),
  FOREIGN KEY (TIPO_PRODUCTO_ID) REFERENCES TIPO_PRODUCTO(ID)
);

CREATE TABLE DIRECCION(
  ID INT AUTO_INCREMENT NOT NULL,
  MUNICIPIO VARCHAR(25) NOT NULL,
  COLONIA VARCHAR(25) NOT NULL,
  CALLE VARCHAR(30) NOT NULL,
  CP VARCHAR(5) NOT NULL,
  NO_EXT VARCHAR(4) NOT NULL,
  NO_INT VARCHAR(3),
  ESTADO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID)
);

CREATE TABLE SUCURSAL(
  ID INT AUTO_INCREMENT NOT NULL,
  NOMBRE VARCHAR(25) NOT NULL,
  LADA VARCHAR(2) NOT NULL,
  TELEFONO VARCHAR(8) NOT NULL,
  DIRECCION_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCION(ID)
);

CREATE TABLE EMPLEADO(
  ID INT AUTO_INCREMENT NOT NULL,
  NOMBRE VARCHAR(25) NOT NULL,
  APELLIDO_PATERNO VARCHAR(25) NOT NULL,
  APELLIDO_MATERNO VARCHAR(25) NOT NULL,
  CORREO_EMPLEADO VARCHAR(40) NOT NULL,
  LADA VARCHAR(2) NOT NULL,
  TELEFONO VARCHAR(8) NOT NULL,
  ROL_EMPLEADO_ID INT NOT NULL,
  BILINGUE_ID INT NOT NULL,
  SUCURSAL_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ROL_EMPLEADO_ID) REFERENCES ROL_EMPLEADO(ID),
  FOREIGN KEY (BILINGUE_ID) REFERENCES BILINGUE(ID),
  FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
);

CREATE TABLE PRODUCTO_SUCURSAL(
  PRODUCTO_CODIGO VARCHAR(5) NOT NULL,
  SUCURSAL_ID INT NOT NULL,
  CANTIDAD INT NOT NULL,
  PRIMARY KEY (PRODUCTO_CODIGO, SUCURSAL_ID),
  FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTO(CODIGO),
  FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
);

CREATE TABLE CLIENTE(
  CODIGO VARCHAR(5) NOT NULL,
  NOMBRE VARCHAR(25) NOT NULL,
  DESCRIPCION VARCHAR(150),
  CORREO VARCHAR(30) NOT NULL,
  LADA VARCHAR(2) NOT NULL,
  TELEFONO VARCHAR(8) NOT NULL,
  DIRECCION_ID INT NOT NULL,
  PRIMARY KEY (CODIGO),
  FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCION(ID)
);

CREATE TABLE SERVICIO(
  ID INT AUTO_INCREMENT NOT NULL,
  FECHA_SOLICITUD DATE NOT NULL,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  HORA_INICIO DATETIME NOT NULL,
  HORA_FIN DATETIME NOT NULL,
  PRECIO DECIMAL(10, 2) NOT NULL,
  DIRECCION_ID INT NOT NULL,
  CLIENTE_CODIGO VARCHAR(5) NOT NULL,
  SUCURSAL_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCION(ID),
  FOREIGN KEY (CLIENTE_CODIGO) REFERENCES CLIENTE(CODIGO),
  FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
);

CREATE TABLE PRODUCTO_SERVICIO(
  PRODUCTO_CODIGO VARCHAR(5) NOT NULL,
  SERVICIO_ID INT NOT NULL,
  CANTIDAD INT NOT NULL,
  PRIMARY KEY (PRODUCTO_CODIGO, SERVICIO_ID),
  FOREIGN KEY (PRODUCTO_CODIGO) REFERENCES PRODUCTO(CODIGO),
  FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(ID)
);
